### ISSUE TITLE
キャラクター役割の最適化（ビジネス学習観点）

### ISSUE THREAD

**Issue by tenchan000517** [tenchan000517/novel#10]
## 🎯 Issue #3: キャラクター役割の最適化（ビジネス学習観点）

**ラベル**: `enhancement`, `medium-priority`, `character-system`  
**関連Epic**: #7  
**優先度**: 中

### 🔍 問題
現在のキャラクター設定がビジネス学習の観点で最適化されておらず、学習効果が限定的。

### 💡 解決策
各キャラクターにビジネス学習における特定の役割を割り当て、学習体験を最大化。

#### 👨‍🎓 高橋誠 - メイン学習者
- **役割**: 理論学習→実践適用の成長軌道を担う主人公
- **学習パターン**: 失敗→指導→理解→実践→成功
- **専門領域**: 全ビジネスフレームワークの段階的習得

#### 👨‍🏫 山田哲也 - 経験豊富なメンター
- **役割**: 各種フレームワークを段階的に指導
- **指導スタイル**: ソクラテス式対話による気づき促進
- **専門領域**: 戦略思考、マネジメント理論、成功哲学

#### 👨‍💻 佐藤健太 - 技術×経営の融合視点
- **役割**: 効率性・最適化重視のアプローチ提供
- **専門領域**: データ分析、プロセス改善、技術戦略
- **学習貢献**: 論理的思考と実装力の重要性を示す

#### 👩‍💼 鈴木美咲 - マーケティング専門家
- **役割**: 顧客中心思考の指導
- **専門領域**: マーケティング戦略、顧客理解、コミュニケーション
- **学習貢献**: 市場視点と伝達技術の重要性を示す

#### 👨‍💼 中村大輔 - 対照的アプローチ
- **役割**: 失敗例・反面教師として学習機会を創出
- **アプローチ**: 短期思考、自己中心的判断
- **学習貢献**: 「やってはいけない」パターンの明示

#### キャラクター設定ファイル更新
- [ ] `data/characters/main/character-takahashi.yaml` - 学習者設定強化
- [ ] `data/characters/sub/character-yamada.yaml` - メンター設定強化
- [ ] `data/characters/main/character-sato.yaml` - 技術×経営視点追加
- [ ] `data/characters/main/character-suzuki.yaml` - マーケティング専門性強化
- [ ] `data/characters/sub/character-nakamura.yaml` - 反面教師設定追加

#### ビジネス指導パターン
- [ ] メンターの指導パターンテンプレート作成
- [ ] 失敗→指導→改善のサイクル設計
- [ ] キャラクター間の対話によるフレームワーク学習パターン

### 💻 実装ファイル
- `data/characters/main/*.yaml`
- `data/characters/sub/*.yaml`
- `src/lib/characters/services/psychology-service.ts`
- `src/lib/characters/services/relationship-service.ts`

### 🎭 キャラクター対話例
```yaml
# 山田メンターの指導例
yamada_teaching_pattern:
  trigger: "高橋が問題設定で困っている"
  approach: "ソクラテス式質問"
  dialogue: 
    - "君は何を解決したいのかな？"
    - "その問題の本質は何だと思う？"
    - "解の質を上げる前に、問いの質はどうだろう？"
  learning_outcome: "ISSUE DRIVEN思考法の理解"
```

### ✅ 受け入れ基準
- [ ] 各キャラクターが明確な学習指導役割を持つ
- [ ] キャラクター成長度スコアが0.6以上に向上
- [ ] 多角的な学習アプローチが実現される
- [ ] キャラクター間の対話で自然にビジネス知識が伝達される

@claude この最適化により、各キャラクターが効果的な学習促進役として機能します。

🤖 Generated with [Claude Code](https://claude.ai/code)

Co-Authored-By: Claude <noreply@anthropic.com>
